### 测试注册接口
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234"
}

###

### 测试登录接口
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234"
}

###

### 测试更新个人信息接口
PUT http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODI1MjYxODgsImV4cCI6MTc4MzEzMDk4OH0.-HREkoItYY9AtzmjOGsxM8MGvn8ByIZsiVs5BKXPWng

{
  "username":"11"
}

###

### 测试更新个人信息接口
PUT http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODI1MjYxODgsImV4cCI6MTc4MzEzMDk4OH0.-HREkoItYY9AtzmjOGsxM8MGvn8ByIZsiVs5BKXPWng

{
  "username":"11"
}

###

### 测试上传简历接口
POST http://localhost:5000/api/upload/resume
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODI1MjYxODgsImV4cCI6MTc4MzEzMDk4OH0.-HREkoItYY9AtzmjOGsxM8MGvn8ByIZsiVs5BKXPWng
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="resume"; filename="胡涵钰_Vue全栈.pdf"
Content-Type: application/pdf

< C:/Users/lenovo/Desktop/胡涵钰_Vue全栈.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

### 测试获取用户信息接口
GET http://localhost:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODI1MjYxODgsImV4cCI6MTc4MzEzMDk4OH0.-HREkoItYY9AtzmjOGsxM8MGvn8ByIZsiVs5BKXPWng

###

### 测试获取问题列表接口
GET http://localhost:5000/api/questions?category=JavaScript&difficulty=medium
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODgzMzkzNTcsImV4cCI6MTc4ODk0NDE1N30.zH_bUnNWg7IFYVnm8xv4aAqPY1xEHgz6V_7ERm0YTFw

###

###测试获取单个问题详情
GET http://localhost:5000/api/questions/6a96932ec73a7b161b76c62e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJkMTczOTMzMjA3NjljZjgxNzNmZGIiLCJpYXQiOjE3ODg0MTY1MTUsImV4cCI6MTc4OTAyMTMxNX0.ZiR52uBK45HJccpFniQeBlWbHjwwJyjf_ooGJG-4ksA